module.exports = {
    "SUCCESS": "SUCCESS",
    "FAILURE": "FAILURE",

    "WORKS": "WORKS",
    "PERFORMERS": "PERFORMERS",
    "RANKINGS": "RANKINGS",

    "NA": "NA",
    "UNKNOWN": "UNKNOWN",
    "UNRANKED": 0,

    "ERROR_INVALID_CACHE_TYPE": "ERROR_INVALID_CACHE_TYPE",
    "ERROR_UNKNOWN_PARTIAL": "ERROR_UNKNOWN_PARTIAL",
    "ERROR_UNIMPLEMENTED": "ERROR_UNIMPLEMENTED",
    "ERROR_ENTRY_EXISTS": "ERROR_ENTRY_EXISTS",
    "ERROR_INVALID_ID": "ERROR_INVALID_ID",

    "OPS_ADD": "OPS_ADD",
    "OPS_UPDATE": "OPS_UPDATE",
    "OPS_DELETE": "OPS_DELETE",

    "PRIME_CACHE_IDENTIFIER": "_isPrimeCache",
}
