module.exports = {
    "SUCCESS": "SUCCESS",
    "FAILURE": "FAILURE",

    "WORKS": "WORKS",
    "PERFORMERS": "PERFORMERS",
    "ATTRIBUTES": "ATTRIBUTES",

    "NA": "NA",
    "BOOLEAN_UNKNOWN": "BOOLEAN_UNKNOWN",
    "DEFAULT_UNFILLED": "DEFAULT_UNFILLED",
    "UNRANKED": 0,

    "ERROR_GENERIC": "ERROR_GENERIC",
    
    "ERROR_INVALID_CACHE_TYPE": "ERROR_INVALID_CACHE_TYPE",
    "ERROR_UNKNOWN_PARTIAL": "ERROR_UNKNOWN_PARTIAL",
    "ERROR_UNIMPLEMENTED": "ERROR_UNIMPLEMENTED",
    "ERROR_ENTRY_EXISTS": "ERROR_ENTRY_EXISTS",
    "ERROR_NO_ENTRY_EXISTS": "ERROR_NO_ENTRY_EXISTS",
    "ERROR_MISSING_INFO": "ERROR_MISSING_INFO",
    "ERROR_INVALID_ID": "ERROR_INVALID_ID",
    "ERROR_NO_CONTENT": "ERROR_NO_CONTENT",
    "ERROR_SERVICE_ERROR": "ERROR_SERVICE_ERROR",
    "ERROR_INVALID_OPERATION": "ERROR_INVALID_OPERATION",
    "ERROR_OUT_OF_BOUNDS": "ERROR_OUT_OF_BOUNDS",
    "ERROR_UNSAFE_OPERATION": "ERROR_UNSAFE_OPERATION",

    "OPS_ADD": "OPS_ADD",
    "OPS_UPDATE": "OPS_UPDATE",
    "OPS_DELETE": "OPS_DELETE",

    "PRIME_CACHE_IDENTIFIER": "_isPrimeCache",

    "SANITIZATION_SEAL_KEY": "_sanitized",

    "MULTI_KEY": "__multi__",
    "RELATION_SEPARATOR": "__",

    "DATATYPE_STRING": "DATATYPE_STRING",
    "DATATYPE_NUMBER": "DATATYPE_NUMBER",
    "DATATYPE_BOOLEAN": "DATATYPE_BOOLEAN",
    "DATATYPE_ANY": "DATATYPE_ANY",

    "ID_SUFFIX_DIGIT_LENGTH": 3,

    "ID_COLUMN_KEY": "_id",
    "DIRPATH_COLUMN_KEY": "_dirpath",
    "FULLFILEPATH_COLUMN_KEY": "_fullpath",
    "CLASS_COLUMN_KEY": "_class",
    "VALUE_COLUMN_KEY": "_value",
    "TIMESTAMP_COLUMN_KEY": "_timestamp",
}
