module.exports = {
    "SUCCESS": "SUCCESS",
    "FAILURE": "FAILURE",

    "WORKS": "WORKS",
    "PERFORMERS": "PERFORMERS",
    "RANKINGS": "RANKINGS",

    "NA": "NA",
    "UNKNOWN": "UNKNOWN",
    "UNRANKED": 0,

    "ERROR_GENERIC": "ERROR_GENERIC",
    
    "ERROR_INVALID_CACHE_TYPE": "ERROR_INVALID_CACHE_TYPE",
    "ERROR_UNKNOWN_PARTIAL": "ERROR_UNKNOWN_PARTIAL",
    "ERROR_UNIMPLEMENTED": "ERROR_UNIMPLEMENTED",
    "ERROR_ENTRY_EXISTS": "ERROR_ENTRY_EXISTS",
    "ERROR_MISSING_INFO": "ERROR_MISSING_INFO",
    "ERROR_INVALID_ID": "ERROR_INVALID_ID",
    "ERROR_NO_CONTENT": "ERROR_NO_CONTENT",
    "ERROR_SERVICE_ERROR": "ERROR_SERVICE_ERROR",

    "OPS_ADD": "OPS_ADD",
    "OPS_UPDATE": "OPS_UPDATE",
    "OPS_DELETE": "OPS_DELETE",

    "PRIME_CACHE_IDENTIFIER": "_isPrimeCache",

    "MULTI_KEY": "__multi__",
    "RELATION_SEPARATOR": "__",
}
